### ISSUE TITLE
赞一个，并求更新

### ISSUE THREAD

**Issue by HDHunter** [iOnesmile/MergeModuleAAR#1]
我工作于游戏公司，帮助游戏Untiy开发者快速集成jar层面的代码，需要合并打出aar，也需要这样的工具。
发现大大的仓库代码似乎有些残缺，可以更详尽点吗，让我们这些小白用起来，并不断完善

**Comment by RuiRay** [comment]
已更新，主入口参见：produce/script/javaMerge/src/com/merge/OneSetup.kt
